### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by isovector** [functional-vilnius/functional-vilnius.github.io#7]
Hi! Are y'all still active? I'd love to meet up and maybe give a talk!

**Comment by vipo** [comment]
Hi,

This page is not up to date because we are lazy. We are not very active but still we are alive! See https://www.meetup.com/functional-vilnius/ for more info.

We are constantly searching for speakers so if you want to speak we could organize a new meetup, probably in the middle of May, because later,  in summer, community becomes very passive. Just drop us a message to info@functionalvilnius.lt with a title and abstract of a talk and we will discuss it.

Thanks!
